
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientProvider from "@/Utils/clientProvider/clientProvider";
import Navbar from "@/Themes/Components/Navbar/Navbar";
import Footer from "@/Themes/Components/Footer/Footer";
import ReduxProvider from "@/Utils/Redux/reduxProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Swift Cars",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ClientProvider>
          <Navbar/>
          {children}
          <Footer/>
        </ClientProvider>
      </body>
    </html>
    </ReduxProvider>
  );
}
